"""Sang Math COMB10 V2 - Hoán vị các phần tử giống nhau.

Manim Community Scene: COMB10. Uses synchronized 48 narration beats and
Typst PNG formulas generated by scripts/prepare_comb10_v2.py.
"""
from __future__ import annotations
import json
import sys
from pathlib import Path
from manim import *

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from comb10_lesson_data import BEATS, CHAPTER_LABELS, unique_words
from series_config import PALETTE as C

config.background_color = C['bg']
config.frame_width = 14.222222
config.frame_height = 8
FONT = 'Noto Sans'
LX, RX = -3.68, 3.10


def word(text, x, y, size=19, color=None, bold=False, max_width=None):
    t = Text(str(text), font=FONT, font_size=size, color=color or C['text'],
             weight='BOLD' if bold else 'NORMAL')
    if max_width and t.width > max_width:
        t.scale_to_fit_width(max_width)
    t.move_to((x, y, 0))
    return t


def label(text, x, y, w=0.84, h=0.66, color=None, font=20, fill=None):
    col = color or C['cyan']
    block = RoundedRectangle(width=w, height=h, corner_radius=.115,
                             stroke_color=col, stroke_width=1.8,
                             fill_color=fill or C['panel_alt'], fill_opacity=1)
    block.move_to((x, y, 0))
    value = word(text, x, y, font, C['text'], True, w-.10)
    return VGroup(block, value)


def headline(group, name):
    group.add(word(name, LX, 2.60, 16, C['cyan'], True, 5.56))


def foot(group, text):
    group.add(word(text, LX, -2.59, 15, C['gold'], True, 5.55))


def token_strip(group, letters, y=1.33, gap=.88, colors=None):
    objects=[]
    for i, ch in enumerate(letters):
        color = (colors[i] if colors else C['cyan'])
        x = LX + (i-(len(letters)-1)/2)*gap
        p=label(ch,x,y,.70,.76,color,20)
        group.add(p);objects.append(p)
    return objects


def mini_grid(group, strings, selected=None, columns=4, top=.45, spacing_x=1.26,
              spacing_y=.49, text_size=16, highlights=None, max_rows=None):
    objs=[]
    for i, s in enumerate(strings):
        if max_rows is not None and i//columns>=max_rows:break
        x=LX+(i%columns-(columns-1)/2)*spacing_x
        y=top-(i//columns)*spacing_y
        col=C['inactive']
        if highlights is not None:
            col=C['green'] if s in highlights else C['red'] if selected is not None else C['inactive']
        elif selected is not None and i<selected:
            col=C['green']
        p=label(s,x,y,spacing_x-.1,spacing_y-.07,col,text_size)
        group.add(p);objs.append(p)
    return objs


def boxes_at(group, texts, positions, y, colors, w=.9):
    objs=[]
    for text,x,color in zip(texts,positions,colors):
        p=label(text,x,y,w,.75,color,18)
        group.add(p);objs.append(p)
    return objs


def identity_view(s):
    g=VGroup();headline(g,'VẬT GIỐNG NHAU → HOÁN VỊ TRÙNG')
    tags=['A₁','A₂','B','C'] if s in (1,2) else ['A','A','B','C']
    colors=[C['cyan'],C['cyan'],C['gold'],C['purple']]
    objs=token_strip(g,tags,1.34,.94,colors)
    if s>=2:
        g.add(CurvedArrow((LX-.45,.84,0),(LX-1.43,.84,0),angle=-1.3,color=C['purple'],stroke_width=2.4))
        g.add(word('ĐỔI HAI A → CÙNG KẾT QUẢ',LX,.57,15,C['purple'],True,5.3))
    arrangements=unique_words('AABC')
    count=[0,0,0,4,12,12][s]
    grid=mini_grid(g,arrangements,count,columns=4,top=.16,spacing_x=1.37,spacing_y=.59,text_size=17)
    foot(g,'24 / 2! = 12 HOÁN VỊ' if s>=3 else 'THỬ GẮN NHÃN RỒI XOÁ NHÃN')
    focus=grid[min(max(count-1,0),len(grid)-1)] if grid else objs[min(s,3)]
    return g,focus


def mama_view(s):
    g=VGroup();headline(g,'MAMA · HAI NHÓM KÝ TỰ TRÙNG')
    tags=['M₁','A₁','M₂','A₂'] if s in (1,2) else list('MAMA')
    objs=token_strip(g,tags,1.45,1.05,[C['purple'],C['cyan'],C['purple'],C['cyan']])
    g.add(label('M : 2!',LX-1.35,.60,2.16,.57,C['purple'],17))
    g.add(label('A : 2!',LX+1.35,.60,2.16,.57,C['cyan'],17))
    allwords=unique_words('MAMA')
    count=[0,0,0,1,6,6][s]
    mini=mini_grid(g,allwords,count,columns=3,top=-.08,spacing_x=1.73,spacing_y=.75,text_size=18)
    foot(g,'4! / (2! × 2!) = 6' if s>=3 else 'MỖI NHÓM CẦN CHIA THEO SỐ CÁCH ĐỔI NHÃN')
    return g,(mini[-1] if mini else objs[s%4])


def banana_view(s):
    g=VGroup();headline(g,'BANANA · BA A, HAI N, MỘT B')
    chars='BANANA'
    cols=[C['gold'] if ch=='B' else C['cyan'] if ch=='A' else C['purple'] for ch in chars]
    tokens=token_strip(g,list(chars),1.58,.81,cols)
    for i,(t,color) in enumerate([('A × 3',C['cyan']),('N × 2',C['purple']),('B × 1',C['gold'])]):
        g.add(label(t,LX+(i-1)*1.8,.72,1.58,.61,color,17))
    # 6 x 10 layout: show a representative sample from all 60 results.
    samples=unique_words('BANANA')[:24]
    count=[0,0,0,8,16,24][s]
    tiles=mini_grid(g,samples,count,columns=6,top=.12,spacing_x=.86,spacing_y=.52,text_size=12)
    foot(g,'6! / (3! × 2!) = 60' if s>=4 else '720 CÁCH CÓ NHÃN, MỖI TỪ LẶP 12 LẦN')
    return g,(tiles[min(count-1,len(tiles)-1)] if count else tokens[min(s,5)])


def general_view(s):
    g=VGroup();headline(g,'CHỨNG MINH CÔNG THỨC TỔNG QUÁT')
    objects=[]
    seq=[('n vị trí',C['cyan']),('n! có nhãn',C['gold']),('k₁! lần',C['purple']),
         ('k₂! lần',C['purple']),('…',C['inactive'])]
    for j,(t,c) in enumerate(seq):
        x=LX + (j-2)*1.16
        box=label(t,x,1.48,1.05,.69,c,14)
        g.add(box);objects.append(box)
    for i in range(1,5):
        g.add(Arrow((LX+(i-2.5)*1.16,1.10,0),(LX+(i-1.5)*1.16,1.10,0),
                    color=C['line'],stroke_width=1.6,max_tip_length_to_length_ratio=.13))
    examples=[('TẤT CẢ KHÁC NHAU','n!'),('MỘT NHÓM GIỐNG NHAU','n! / k!'),
              ('NHIỀU NHÓM GIỐNG NHAU','CHIA TÍCH CÁC GIAI THỪA')]
    for j,(a,b) in enumerate(examples):
        y=.43-j*.78
        g.add(word(a,LX-1.2,y,14,C['muted'],True,3.25),
              label(b,LX+1.65,y,2.31,.61,C['green'] if j<=s//2 else C['inactive'],15))
    foot(g,'n = k₁ + k₂ + ··· + kᵣ' if s<3 else 'SỐ KẾT QUẢ = n! / (k₁! k₂! … kᵣ!)')
    return g,objects[min(s,4)]


def block_view(s):
    g=VGroup();headline(g,'GỘP KHỐI AAA · BÀI TOÁN KỀ NHAU')
    if s<2:
        tokens=token_strip(g,list('BANANA'),1.40,.82)
        focus=tokens[1]
    else:
        tokens=boxes_at(g,['AAA','B','N','N'],[LX-1.83,LX-.63,LX+.60,LX+1.83],1.36,
                    [C['cyan'],C['gold'],C['purple'],C['purple']],1.03)
        focus=tokens[0]
    g.add(word('BA CHỮ A ĐƯỢC COI LÀ MỘT VẬT',LX,.60,17,C['cyan'],True,5.4))
    sample=unique_words('BANANA')
    strings=[w for w in sample if 'AAA' in w]
    n=[0,0,0,4,12,12][s]
    tiles=mini_grid(g,strings,n,columns=4,top=.10,spacing_x=1.34,spacing_y=.59,text_size=15)
    foot(g,'4! / 2! = 12' if s>=2 else 'CÓ MỘT KHỐI AAA, MỘT B VÀ HAI N')
    return g,(tiles[min(n-1,len(tiles)-1)] if n else focus)


def gaps_view(s):
    g=VGroup();headline(g,'KHÔNG CÓ HAI A NÀO KỀ NHAU')
    positions=[LX-2.35,LX-1.56,LX-.78,LX-.00,LX+.78,LX+1.56,LX+2.35]
    values=['_','B','_','N','_','N','_']
    focus=None
    for j,(x,value) in enumerate(zip(positions,values)):
        filled=value
        if s>=3 and j in (0,2,4):filled='A'
        color=C['cyan'] if j%2==0 else C['purple']
        p=label(filled,x,1.49,.68,.74,color,18)
        g.add(p)
        if j==2:focus=p
    g.add(word('CÓ 4 KHOẢNG – CHỌN 3 KHOẢNG',LX,.65,17,C['gold'],True,5.5))
    for i,(name,formula) in enumerate([('XẾP B N N','3! / 2! = 3'),
                 ('CHỌN BA KHOẢNG','C(4,3) = 4'),('TỔNG CÁCH','3 × 4 = 12')]):
        y=-.02-i*.70
        g.add(word(name,LX-1.35,y,15,C['muted'],True,2.75))
        g.add(label(formula,LX+1.48,y,2.79,.57,C['green'] if i<=max(0,s-2) else C['inactive'],15))
    foot(g,'MỖI KHOẢNG TỐI ĐA MỘT CHỮ A')
    return g,focus


def boundary_view(s):
    g=VGroup();headline(g,'BẮT ĐẦU B HOẶC KẾT THÚC A')
    ban=unique_words('BANANA')
    starts={w for w in ban if w.startswith('B')}
    ends={w for w in ban if w.endswith('A')}
    circ1=Circle(radius=1.10,color=C['cyan'],stroke_width=2.7,fill_color=C['cyan'],fill_opacity=.10)
    circ2=Circle(radius=1.10,color=C['purple'],stroke_width=2.7,fill_color=C['purple'],fill_opacity=.10)
    circ1.move_to((LX-.87,.38,0));circ2.move_to((LX+.87,.38,0))
    g.add(circ1,circ2)
    g.add(word('B đầu',LX-1.57,.63,14,C['cyan'],True,1.3))
    g.add(word('A cuối',LX+1.58,.63,14,C['purple'],True,1.3))
    v1='10' if s>=0 else '?';v2='30' if s>=1 else '?';v3='6' if s>=2 else '?'
    g.add(word(v1,LX-1.56,.07,20,C['cyan'],True),
          word(v2,LX+1.56,.07,20,C['purple'],True),
          label(v3,LX,-.23,.70,.55,C['gold'],17))
    g.add(label('GIAO: 6',LX-1.46,-1.20,2.39,.58,C['gold'] if s>=2 else C['inactive'],16))
    g.add(label('HỢP: 34',LX+1.46,-1.20,2.39,.58,C['green'] if s>=4 else C['inactive'],16))
    foot(g,'10 + 30 − 6 = 34' if s>=4 else 'HAI TẬP HỢP CÓ PHẦN GIAO')
    return g,circ1 if s%2==0 else circ2


def challenge_view(s):
    g=VGroup();headline(g,'AABBC · LOẠI CẶP AA / BB')
    chars='AABBC';cols=[C['cyan'],C['cyan'],C['purple'],C['purple'],C['gold']]
    tokens=token_strip(g,list(chars),1.61,.93,cols)
    arrangement=unique_words('AABBC')
    # Display all 30 results. Keep the condition visible through persistent color.
    flag={w for w in arrangement if 'AA' not in w}
    high=None if s<2 else flag if s==3 else {w for w in arrangement if 'AA' not in w and 'BB' not in w} if s==4 else flag
    tiles=mini_grid(g,arrangement,selected=30 if s>=2 else min(12,s*12),
                    columns=6,top=.85,spacing_x=.89,spacing_y=.51,text_size=11,
                    highlights=high)
    foot(g,'30 − 12 = 18' if s==3 else '30 − 12 − 12 + 6 = 12' if s>=4 else 'TỔNG CỘNG 30 HOÁN VỊ')
    return g,tiles[min(s*4,len(tiles)-1)] if tiles else tokens[0]

VIEWS={
    'identity':identity_view, 'mama':mama_view, 'banana':banana_view,
    'general':general_view, 'block':block_view, 'gaps':gaps_view,
    'boundary':boundary_view, 'challenge':challenge_view
}


def formula_image(name):
    image_path=ROOT/'assets'/'comb10v2'/f'{name}.png'
    if not image_path.exists():
        raise FileNotFoundError(f'Chưa có công thức Typst: {image_path}. Hãy chạy prepare_comb10_v2.py.')
    graphic=ImageMobject(str(image_path))
    graphic.scale_to_fit_width(min(graphic.width, 5.62))
    if graphic.height>.80:graphic.scale_to_fit_height(.80)
    graphic.move_to((RX,-1.10,0))
    return graphic


class COMB10(Scene):
    def setup(self):
        voice_manifest=ROOT/'voice'/'comb10_voice_manifest.json'
        if not voice_manifest.exists():
            raise FileNotFoundError('Hãy chạy: python scripts/prepare_comb10_v2.py --voice off')
        self.meta=json.loads(voice_manifest.read_text(encoding='utf-8'))
        if self.meta['beats']!=len(BEATS):raise ValueError('Voice manifest mismatch')
        self.previous=None
        self.add(word('SANG MATH  /  ĐẠI SỐ TỔ HỢP',-3.7,3.62,19,C['cyan'],True,6.10))
        self.add(word('COMB10  /  HOÁN VỊ LẶP',3.68,3.62,17,C['muted'],True,5.1))
        self.add(Line((-6.85,3.32,0),(6.85,3.32,0),color=C['line'],stroke_width=1.1))
        for cx,width in ((LX,6.18),(RX,6.46)):
            bg=RoundedRectangle(width=width,height=6.16,corner_radius=.16,
                stroke_color=C['line'],stroke_width=1.3,
                fill_color=C['panel'],fill_opacity=1)
            bg.move_to((cx,0,0));self.add(bg)
        self.add(Line((-6.85,-3.32,0),(6.85,-3.32,0),color=C['line'],stroke_width=1.1))

    def make_right(self,b,index):
        heading=VGroup(word(CHAPTER_LABELS[b.section],RX,2.67,15,C['purple'],True,5.78),
                       word(b.heading,RX,2.05,20,C['gold'],True,5.72))
        statements=VGroup(*[word('• '+line,RX,1.24-i*.60,17,C['text'],False,5.75)
                            for i,line in enumerate(b.lines)])
        equation=formula_image(b.formula) if b.formula else word('QUAN SÁT → CHỨNG MINH',RX,-1.10,17,C['cyan'],True,5.65)
        conclusion=VGroup(Line((.25,-1.76,0),(6.17,-1.76,0),color=C['line'],stroke_width=1.1),
                         word(b.takeaway,RX,-2.35,16,C['green'],True,5.76))
        counter=word(f'{index+1:02d} / {len(BEATS)}',0,-3.70,15,C['muted'],True)
        return heading,statements,equation,conclusion,counter

    def show_beat(self,index,b):
        metadata=self.meta['clips'][f'{index:03}']
        if metadata.get('file'):
            audio=ROOT/'voice'/metadata['file']
            if not audio.is_file():raise FileNotFoundError(audio)
            self.add_sound(str(audio))
        duration=max(b.min_seconds,float(metadata.get('duration',0))+.85)
        art,focus=VIEWS[b.section](b.state)
        head,statements,eq,conclusion,counter=self.make_right(b,index)
        if self.previous is None:
            self.play(FadeIn(art),FadeIn(head),FadeIn(counter),run_time=1.0)
        else:
            oart,ohead,olines,oeq,oconc,ocounter=self.previous
            self.play(FadeOut(oart),FadeIn(art),FadeOut(ohead),FadeIn(head),
                      FadeOut(olines),FadeOut(oeq),FadeOut(oconc),
                      ReplacementTransform(ocounter,counter),run_time=1.0)
        special=0.0
        if b.section=='identity' and b.state==2:
            # A1 and A2 actually exchange positions: with labels these are
            # different permutations, but after deleting labels they coincide.
            self.play(Swap(art[1],art[2]),run_time=1.35)
            special=1.35
        self.play(Indicate(focus,color=C['gold'],scale_factor=1.06),run_time=1.6)
        for line in statements:
            self.play(FadeIn(line,shift=.08*UP),run_time=1.10)
        self.play(FadeIn(eq,shift=.08*UP),run_time=1.20)
        self.play(FadeIn(conclusion),run_time=.95)
        self.play(Circumscribe(conclusion[-1],color=C['green'],buff=.085),run_time=1.20)
        spent=1+special+1.6+3*1.10+1.20+.95+1.20
        if duration>spent:self.wait(duration-spent)
        self.previous=(art,head,statements,eq,conclusion,counter)

    def construct(self):
        for i,b in enumerate(BEATS):self.show_beat(i,b)
        self.play(*[FadeOut(x) for x in self.previous],run_time=1)
        ending=VGroup(word('COMB10  ·  HOÁN VỊ LẶP',0,.55,31,C['cyan'],True,11.5),
                      word('HIỂU ĐẾM TRÙNG TRƯỚC KHI DÙNG CÔNG THỨC',0,-.34,20,C['gold'],True,12.0))
        self.play(FadeIn(ending),run_time=1.35)
        self.wait(2.85)
